# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Plant Bacteriology Lab
short_labname: PBL
email: kun8948@snu.ac.kr
logo: logo.png
description: > # 다음 줄에 연구실 소개 입력
  Plant Bacteriology Lab, Seoul National University; 서울대학교 종업생명과학대학 오창식 교수 식물세균병학 연구실;
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  
google-site-verification:

# Build settings
markdown: kramdown
include: ['_pages', '_news']
plugins: [jekyll-seo-tag,jekyll-paginate]

paginate: 5
paginate_path: "/news/page:num/"
